#! /usr/bin/env python3

################################################################################
#
# Copyright 2018-2025 Silvio Ricardo Cordeiro, Van Tuan Bui, Carlos Ramisch, Agata Savary
#
# average_of_paraphrase_evaluations.py is part of parseme-utilities
#
# parseme-utilities is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# parseme/sharedtask-data is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with parseme-utilities.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
# The script scans one or more files generated by the evaluate.py script (for MWE paraphrasing), for instance:
#
#-------------------------------------- /home/savary/PARSEME/PARSEME-corpora/Gitlab/sharedtask-data-dev/2.0/preliminary-sharedtask-data/subtask2_trial/FR/prediction.json --------------------------------------
# PERFORMANCE :
# Average f-bertscore for the current system: 100.00
# Number of evaluated elements: 2
# Number of elements with a 0 score (MWE not deleted): 0
# 
# 
# DIVERSITY :
# Entropy, variety, balance for the current system:        1.386, 4, 1.000
# Entropy, variety, balance for the minimal reference:     0.693, 2, 1.000
# Entropy, variety, balance for the creative reference:    2.773, 16, 1.000
#
################################################################################
# The scores are then agregated (whenever appropriate) and exported in a JSON file
################################################################################
# Parameters: 
#      the total number of languages in the competition
#      directory of system results, with one folder per language, containing a results.txt file generate by evaluate.py
#      output file for the scores in json
#      output file for the scores in html
#
# Sample call:
#   ./average_of_paraphrase_evaluations.py 17 ../../../system-results/subtask2/trial-system/ scores.json scores.html
#
# Sample json outcome:
#   {"Global-BERTScore": 7.724705882352941, 
#    "All_scores": [
#        {"language": "FR", "scores": 
#           {"bertscore": 100.0, "div_current_entropy": 1.386, "div_current_variety": 4, 
#            "div_current_balance": 1.0, "div_min_entropy": 0.693, "div_min_variety": 2, "div_min_balance": 1.0, 
#            "div_crea_entropy": 2.773, "div_crea_variety": 16, "div_crea_balance": 1.0}}, 
#        {"language": "EN", "scores": 
#           {"bertscore": 31.32, "div_current_entropy": 1.099, "div_current_variety": 3, "div_current_balance": 1.0,
#            "div_min_entropy": 1.386, "div_min_variety": 4, "div_min_balance": 1.0, 
#            "div_crea_entropy": 2.941, "div_crea_variety": 20, "div_crea_balance": 0.982}}]}
################################################################################

import argparse
import collections
import math
import os
import re
import sys
import json

##########################################

## Regular expressions to extract useful data from the stdout of evaluate.py
RE_BERT = re.compile(r'(f-bertscore)[ a-z\:]+([0-9\.]+)')
RE_DIV_CURRENT = re.compile(r'Entropy, variety, balance for the (current) system:\s*([0-9\.]+), ([0-9\.]+), ([0-9\.]+)')
RE_DIV_MIN = re.compile(r'Entropy, variety, balance for the (minimal) reference:\s*([0-9\.]+), ([0-9\.]+), ([0-9\.]+)')
RE_DIV_CREA = re.compile(r'Entropy, variety, balance for the (creative) reference:\s*([0-9\.]+), ([0-9\.]+), ([0-9\.]+)')

#Default name of the result file
RES_FILE = "results.txt"

def dir_path(string):
    if os.path.isdir(string):
        return string
    else:
        raise NotADirectoryError(string)

parser = argparse.ArgumentParser(description="""
        Calculate macro-average of paraphrasing scores from multiple evaluate.py output files.""")
parser.add_argument("nb_langs",  help="""Total number of languages in the competition""", type= int)
parser.add_argument("result_dir", help="""Directory of system results, with one folder per language""", type=dir_path)
parser.add_argument("out_json",  help="""The output json file for the average scores""", type=argparse.FileType('w'))
parser.add_argument("out_html",  help="""The output html file for the average scores""", type=argparse.FileType('w'))

#parser.add_argument("evaluation_files", nargs='+', type=argparse.FileType('r'),
#        help="""Files that were produced as output of evaluate.py""")


def format_float(value: float):
    r"""Return pretty-formatted float."""
    return "{:.2f}".format(value)


##########################################
class Main(object):
    def __init__(self, args):
        self.args = args

    def run(self):
    
        # Extract relevant data from all the input filres
        #results = self.parse_files(self.args.evaluation_files)
        print("Loading scores...")
        results = self.parse_files(self.args.result_dir)
        
        #Aggregate the bert-scores
        bert_ave = self.average_bert(self.args.nb_langs, results)
        all_results = {"Global-BERTScore": bert_ave, "All_scores": results}
        
        # Generate JSON with all scores for a system
        print("Generating .json file with average scores...")
        self.generate_json(all_results, self.args.out_json)
                
        # Generate HTML with all scores for a system
        print("Generating .html file with average scores...")
        self.generate_html(all_results, len(results), self.args.nb_langs, self.args.out_html)

##########################################
    def parse_files(self,result_dir) -> (int, dict):
        r"""Return the number of laguages covered by a system, and useful data from a directory of files generated by evaluate.py, with 1 folder per language code
        e.g. 
        [{'language': 'EN', 'scores': {'bertscore': 31.32, 'div_current_entropy': 1.099, 'div_current_variety': 3, 'div_current_balance': 1.0, \ 
          'div_min_entropy': 1.386, 'div_min_variety': 4, 'div_min_balance': 1.0, 'div_crea_entropy': 2.941, 'div_crea_variety': 20, 'div_crea_balance': 0.982}}, \
         {'language': 'FR', 'scores': {'bertscore': 100.0, 'div_current_entropy': 1.386, 'div_current_variety': 4, 'div_current_balance': 1.0, \
          'div_min_entropy': 0.693, 'div_min_variety': 2, 'div_min_balance': 1.0, 'div_crea_entropy': 2.773, 'div_crea_variety': 16, 'div_crea_balance': 1.0}}]
        """
        RESULTS = [] #Results from all files
        
        langs = os.listdir(result_dir)
        langs.sort()
        
        for lang in langs:
            
            res_file_path = os.path.join(result_dir, lang, RES_FILE)
            if os.path.isfile(res_file_path) and os.access(res_file_path, os.R_OK):
                res_file = open(res_file_path, 'r+')
                RES = {}
                RES["language"] = lang
                scores = {}
                lines = res_file.read().split("\n")
                for line in lines:
                    res=self.parse_line(line)
                    if res:
                        scores.update(res[0])
                RES["scores"] = scores 
                RESULTS.append(RES)  
            else:
                print("File", res_file_path, "not found. The scores for this language are considered 0.")
            
        
        return RESULTS
        
##########################################
    def parse_line(self,line: str) -> list:
        r"""Return useful data from a file generated by evaluate.py
        e.g. {'bertscore': 100.0}
             OR
             {'div_current_entropy': 1.386, 'div_current_variety': 4.0, 'div_current_balance': 1.0}
             OR
             {'div_min_entropy': 0.693, 'div_min_variety': 2.0, 'div_min_balance': 1.0}
             OR
             {'div_crea_entropy': 2.773, 'div_crea_variety': 16.0, 'div_crea_balance': 1.0}
        """
    
        bertscore = RE_BERT.findall(line) 
        if bertscore:
            #print(bertscore)
            bertscore_dict = {'bertscore': float(bertscore[0][1])}
            return [bertscore_dict]
            #print("BERTSCORE:",bertscore)
    
        div_current = RE_DIV_CURRENT.findall(line)
        if div_current:
            div_current_dict = {}
            div_current_dict['div_current_entropy'] = float(div_current[0][1])
            div_current_dict['div_current_variety'] = int(div_current[0][2])
            div_current_dict['div_current_balance'] = float(div_current[0][3])
            return [div_current_dict]
            #print("DIV_CURRENT:",div_current)
    
        div_min = RE_DIV_MIN.findall(line)
        if div_min:
            div_min_dict = {}
            div_min_dict['div_min_entropy'] = float(div_min[0][1])
            div_min_dict['div_min_variety'] = int(div_min[0][2])
            div_min_dict['div_min_balance'] = float(div_min[0][3])
            return [div_min_dict]
            #print("DIV_MIN:",div_min)
    
        div_crea = RE_DIV_CREA.findall(line)
        if div_crea:
            div_crea_dict = {}
            div_crea_dict['div_crea_entropy'] = float(div_crea[0][1])
            div_crea_dict['div_crea_variety'] = int(div_crea[0][2])
            div_crea_dict['div_crea_balance'] = float(div_crea[0][3])
            return [div_crea_dict]
            #print("DIV_CREA:",div_crea)
            
        return([])
        
##########################################
    def average_bert(self,nb_langs,results: dict):
       r"""From a list of results which looks like the reult of parse_files, aggregate all bert-scores into an average"""
       
       bert_aggr = float(0)
       for lang_res in results:
           bertscore = float(lang_res["scores"]["bertscore"])
           bert_aggr = bert_aggr + bertscore
       return(bert_aggr/nb_langs)
        
##########################################
    def generate_json(self, results, out_json):
        r'''Generate the scores.json file to the specified output_path. The results are of the form: 
           {'Global-BERT-score': 65.66, 
            'All_scores': {'language': 'EN', 'scores': {'bertscore': 31.32, 'div_current_entropy': 1.099, 'div_current_variety': 3, 'div_current_balance': 1.0, 
                           'div_min_entropy': 1.386, 'div_min_variety': 4, 'div_min_balance': 1.0, 'div_crea_entropy': 2.941, 'div_crea_variety': 20, 'div_crea_balance': 0.982}}, 
                          {'language': 'FR', 'scores': {'bertscore': 100.0, 'div_current_entropy': 1.386, 'div_current_variety': 4, 'div_current_balance': 1.0, 
                           'div_min_entropy': 0.693, 'div_min_variety': 2, 'div_min_balance': 1.0, 'div_crea_entropy': 2.773, 'div_crea_variety': 16, 'div_crea_balance': 1.0}}}
        '''
        
        out_json.write(json.dumps(results))

##########################################
    def generate_html(self, results, nb_langs_sys, nb_langs_total, out_html):
        r'''Generate the scores.json file to the specified output_path. 
            nb_langs_sys is the number of langauges covered by the system
            nb_langs_total is the total number of langauges in the competition
            The results are of the form: 
            {'Global-BERT-score': 65.66, 
             'All_scores': {'language': 'EN', 'scores': {'bertscore': 31.32, 'div_current_entropy': 1.099, 'div_current_variety': 3, 'div_current_balance': 1.0, 
                            'div_min_entropy': 1.386, 'div_min_variety': 4, 'div_min_balance': 1.0, 'div_crea_entropy': 2.941, 'div_crea_variety': 20, 'div_crea_balance': 0.982}}, 
                           {'language': 'FR', 'scores': {'bertscore': 100.0, 'div_current_entropy': 1.386, 'div_current_variety': 4, 'div_current_balance': 1.0, 
                            'div_min_entropy': 0.693, 'div_min_variety': 2, 'div_min_balance': 1.0, 'div_crea_entropy': 2.773, 'div_crea_variety': 16, 'div_crea_balance': 1.0}}}
        '''
        s = self._html(results, nb_langs_sys, nb_langs_total)
        out_html.write(s)

#####################################################
    def _html(self, results, nb_langs_sys, nb_langs_total):
        r'''Generate the HTML code for a detailed scoring of one system. '''
        s = (
            '<!DOCTYPE html>\n'
            '<html>\n'
            '<head>\n'
            '<style>\n'
            '.styled-table {\n'
            '\tborder-collapse: collapse;\n'
            '\tmargin: 14px 0;\n'
            '\tmargin-left: 60px;\n'
            '\tfont-size: 0.9em;\n'
            '\tfont-family: sans-serif;\n'
            '\tmin-width: 400px;\n'
            '\tbox-shadow: 0 0 20px rgba(0, 0, 0, 0.15);\n'
            '}\n'
            '.styled-table thead tr {\n'
            '\tbackground-color: #34495e;\n'
            '\tborder: 1px solid #ffffff;\n'
            '\tcolor: #ffffff;\n'
            '\ttext-align: center;\n'
            '}\n'
            '.styled-table th,\n'
            '.styled-table td {\n'
            '\tpadding: 12px 15px;\n'
            '\ttext-align: center;\n'
            '\tmin-width: 45px;\n'
            '}\n'
            '.styled-table tbody tr {\n'
            '\tborder-bottom: 1px solid #dddddd;\n'
            '}\n'
            '.styled-table tbody tr:nth-of-type(even) {\n'
            '\tbackground-color: #f3f3f3;\n'
            '}\n'
            '.styled-table tbody tr:last-of-type {\n'
            '\tborder-bottom: 2px solid #34495e;\n'
            '</style>\n'
            '</head>\n'
            '<body>\n'
            '<p style="line-height: 65%;"> <br> </p>\n'
        )

        s += self._html_macroavg(results, nb_langs_sys, nb_langs_total)
        s += self._html_lang_spec(results)

        # Closing
        s += '</body>\n'
        s += '</html>\n'
        
        return s

#####################################################
    def _html_macroavg(self, results, nb_langs_sys, nb_langs_total):
        r'''Generate the HTML code for the global scoring of one system'''
        s = '<h1 style="color: steelblue;">General scores</h1>\n'
        s += '<table class="styled-table">\n'
        s += '<thead>\n'
        s += '\t<tr>\n'
        s += '\t\t<th>#Langs</th>\n'
        s += '\t\t<th>Global BERTScore</th>\n'
        s += '\t</tr>\n'
        s += '</thead>\n'
        s += '<tbody>\n'
        s += '\t<tr>\n'
        s += '\t\t<th>' + str(nb_langs_sys) + "/" + str(nb_langs_total) + '</th>\n'
        s += '\t\t<th>' + format_float(results["Global-BERTScore"]) + '</th>\n'
        s += '\t</tr>\n'
        s += '</tbody>\n'
        s += '</table>\n'
        s += '<br>\n'
        return s
        
#####################################################
    def _html_lang_spec(self, results):
        r'''Generate the HTML code for a language-specific scoring of one system'''
        
        s = '<h1 style="color: steelblue;">Language-specific scores</h1>\n'
        s += '<br>\n'
        s += '<table class="styled-table">\n'
        s += '<thead>\n'
        s += '\t<tr>\n'
        s += '\t\t<th rowspan="2">Language</th>\n'
        s += '\t\t<th rowspan="2">Average BERTScore</th>\n'
        s += '\t\t<th colspan="3">Diversity of new words</th>\n'
        s += '\t</tr>\n'
        
        s += '\t<tr>\n'
        s += '\t\t<th>Richness</th>\n'
        s += '\t\t<th>Shannon Evenness</th>\n'
        s += '\t\t<th>Shannon-Weaver Entropy</th>\n'
        s += '\t</tr>\n'        
        s += '</thead>\n'
        
        s += '<tbody>\n'
        
        for lang_scores in results["All_scores"]:
            s += '\t<tr>\n'
            s += '\t\t<th>' + lang_scores["language"] + '</th>\n'
            s += '\t\t<th>' + format_float(lang_scores["scores"]["bertscore"]) + '</th>\n'
            s += '\t\t<th>' + str(lang_scores["scores"]["div_current_variety"]) + '</th>\n'
            s += '\t\t<th>' + format_float(lang_scores["scores"]["div_current_balance"]) + '</th>\n'
            s += '\t\t<th>' + format_float(lang_scores["scores"]["div_current_entropy"]) + '</th>\n'
            s += '\t</tr>\n'
            
        s += '</tbody>\n'
        return s

#####################################################

if __name__ == "__main__":
    Main(parser.parse_args()).run()
